//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./example_types');
//HELPER FUNCTIONS AND STRUCTURES

var StingyExampleService_DoSomethingSimple_args = function(args) {
  this.foo = null;
  if (args) {
    if (args.foo !== undefined && args.foo !== null) {
      this.foo = args.foo;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field foo is unset!');
    }
  }
};
StingyExampleService_DoSomethingSimple_args.prototype = {};
StingyExampleService_DoSomethingSimple_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.foo = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StingyExampleService_DoSomethingSimple_args.prototype.write = function(output) {
  output.writeStructBegin('StingyExampleService_DoSomethingSimple_args');
  if (this.foo !== null && this.foo !== undefined) {
    output.writeFieldBegin('foo', Thrift.Type.STRING, 1);
    output.writeString(this.foo);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var StingyExampleService_DoSomethingSimple_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
StingyExampleService_DoSomethingSimple_result.prototype = {};
StingyExampleService_DoSomethingSimple_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StingyExampleService_DoSomethingSimple_result.prototype.write = function(output) {
  output.writeStructBegin('StingyExampleService_DoSomethingSimple_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var StingyExampleService_DoSomethingWithAnInt_args = function(args) {
  this.someInt = null;
  if (args) {
    if (args.someInt !== undefined && args.someInt !== null) {
      this.someInt = args.someInt;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field someInt is unset!');
    }
  }
};
StingyExampleService_DoSomethingWithAnInt_args.prototype = {};
StingyExampleService_DoSomethingWithAnInt_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.someInt = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StingyExampleService_DoSomethingWithAnInt_args.prototype.write = function(output) {
  output.writeStructBegin('StingyExampleService_DoSomethingWithAnInt_args');
  if (this.someInt !== null && this.someInt !== undefined) {
    output.writeFieldBegin('someInt', Thrift.Type.I64, 1);
    output.writeI64(this.someInt);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var StingyExampleService_DoSomethingWithAnInt_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
StingyExampleService_DoSomethingWithAnInt_result.prototype = {};
StingyExampleService_DoSomethingWithAnInt_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StingyExampleService_DoSomethingWithAnInt_result.prototype.write = function(output) {
  output.writeStructBegin('StingyExampleService_DoSomethingWithAnInt_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var StingyExampleService_DoSomethingWithABool_args = function(args) {
  this.someBool = null;
  if (args) {
    if (args.someBool !== undefined && args.someBool !== null) {
      this.someBool = args.someBool;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field someBool is unset!');
    }
  }
};
StingyExampleService_DoSomethingWithABool_args.prototype = {};
StingyExampleService_DoSomethingWithABool_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.someBool = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StingyExampleService_DoSomethingWithABool_args.prototype.write = function(output) {
  output.writeStructBegin('StingyExampleService_DoSomethingWithABool_args');
  if (this.someBool !== null && this.someBool !== undefined) {
    output.writeFieldBegin('someBool', Thrift.Type.BOOL, 1);
    output.writeBool(this.someBool);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var StingyExampleService_DoSomethingWithABool_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
StingyExampleService_DoSomethingWithABool_result.prototype = {};
StingyExampleService_DoSomethingWithABool_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StingyExampleService_DoSomethingWithABool_result.prototype.write = function(output) {
  output.writeStructBegin('StingyExampleService_DoSomethingWithABool_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var StingyExampleService_DoSomethingComplicated_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.SomethingComplicatedRequest(args.request);
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field request is unset!');
    }
  }
};
StingyExampleService_DoSomethingComplicated_args.prototype = {};
StingyExampleService_DoSomethingComplicated_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.SomethingComplicatedRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StingyExampleService_DoSomethingComplicated_args.prototype.write = function(output) {
  output.writeStructBegin('StingyExampleService_DoSomethingComplicated_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var StingyExampleService_DoSomethingComplicated_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.SomethingComplicatedResponse(args.success);
    }
  }
};
StingyExampleService_DoSomethingComplicated_result.prototype = {};
StingyExampleService_DoSomethingComplicated_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.SomethingComplicatedResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StingyExampleService_DoSomethingComplicated_result.prototype.write = function(output) {
  output.writeStructBegin('StingyExampleService_DoSomethingComplicated_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var StingyExampleServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
StingyExampleServiceClient.prototype = {};
StingyExampleServiceClient.prototype.seqid = function() { return this._seqid; };
StingyExampleServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
StingyExampleServiceClient.prototype.DoSomethingSimple = function(foo, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_DoSomethingSimple(foo);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_DoSomethingSimple(foo);
  }
};

StingyExampleServiceClient.prototype.send_DoSomethingSimple = function(foo) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('DoSomethingSimple', Thrift.MessageType.CALL, this.seqid());
  var args = new StingyExampleService_DoSomethingSimple_args();
  args.foo = foo;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StingyExampleServiceClient.prototype.recv_DoSomethingSimple = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StingyExampleService_DoSomethingSimple_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('DoSomethingSimple failed: unknown result');
};
StingyExampleServiceClient.prototype.DoSomethingWithAnInt = function(someInt, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_DoSomethingWithAnInt(someInt);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_DoSomethingWithAnInt(someInt);
  }
};

StingyExampleServiceClient.prototype.send_DoSomethingWithAnInt = function(someInt) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('DoSomethingWithAnInt', Thrift.MessageType.CALL, this.seqid());
  var args = new StingyExampleService_DoSomethingWithAnInt_args();
  args.someInt = someInt;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StingyExampleServiceClient.prototype.recv_DoSomethingWithAnInt = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StingyExampleService_DoSomethingWithAnInt_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('DoSomethingWithAnInt failed: unknown result');
};
StingyExampleServiceClient.prototype.DoSomethingWithABool = function(someBool, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_DoSomethingWithABool(someBool);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_DoSomethingWithABool(someBool);
  }
};

StingyExampleServiceClient.prototype.send_DoSomethingWithABool = function(someBool) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('DoSomethingWithABool', Thrift.MessageType.CALL, this.seqid());
  var args = new StingyExampleService_DoSomethingWithABool_args();
  args.someBool = someBool;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StingyExampleServiceClient.prototype.recv_DoSomethingWithABool = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StingyExampleService_DoSomethingWithABool_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('DoSomethingWithABool failed: unknown result');
};
StingyExampleServiceClient.prototype.DoSomethingComplicated = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_DoSomethingComplicated(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_DoSomethingComplicated(request);
  }
};

StingyExampleServiceClient.prototype.send_DoSomethingComplicated = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('DoSomethingComplicated', Thrift.MessageType.CALL, this.seqid());
  var args = new StingyExampleService_DoSomethingComplicated_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StingyExampleServiceClient.prototype.recv_DoSomethingComplicated = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StingyExampleService_DoSomethingComplicated_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('DoSomethingComplicated failed: unknown result');
};
var StingyExampleServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
StingyExampleServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
StingyExampleServiceProcessor.prototype.process_DoSomethingSimple = function(seqid, input, output) {
  var args = new StingyExampleService_DoSomethingSimple_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.DoSomethingSimple.length === 1) {
    Q.fcall(this._handler.DoSomethingSimple, args.foo)
      .then(function(result) {
        var result_obj = new StingyExampleService_DoSomethingSimple_result({success: result});
        output.writeMessageBegin("DoSomethingSimple", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("DoSomethingSimple", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.DoSomethingSimple(args.foo, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new StingyExampleService_DoSomethingSimple_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("DoSomethingSimple", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("DoSomethingSimple", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
StingyExampleServiceProcessor.prototype.process_DoSomethingWithAnInt = function(seqid, input, output) {
  var args = new StingyExampleService_DoSomethingWithAnInt_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.DoSomethingWithAnInt.length === 1) {
    Q.fcall(this._handler.DoSomethingWithAnInt, args.someInt)
      .then(function(result) {
        var result_obj = new StingyExampleService_DoSomethingWithAnInt_result({success: result});
        output.writeMessageBegin("DoSomethingWithAnInt", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("DoSomethingWithAnInt", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.DoSomethingWithAnInt(args.someInt, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new StingyExampleService_DoSomethingWithAnInt_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("DoSomethingWithAnInt", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("DoSomethingWithAnInt", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
StingyExampleServiceProcessor.prototype.process_DoSomethingWithABool = function(seqid, input, output) {
  var args = new StingyExampleService_DoSomethingWithABool_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.DoSomethingWithABool.length === 1) {
    Q.fcall(this._handler.DoSomethingWithABool, args.someBool)
      .then(function(result) {
        var result_obj = new StingyExampleService_DoSomethingWithABool_result({success: result});
        output.writeMessageBegin("DoSomethingWithABool", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("DoSomethingWithABool", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.DoSomethingWithABool(args.someBool, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new StingyExampleService_DoSomethingWithABool_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("DoSomethingWithABool", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("DoSomethingWithABool", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
StingyExampleServiceProcessor.prototype.process_DoSomethingComplicated = function(seqid, input, output) {
  var args = new StingyExampleService_DoSomethingComplicated_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.DoSomethingComplicated.length === 1) {
    Q.fcall(this._handler.DoSomethingComplicated, args.request)
      .then(function(result) {
        var result_obj = new StingyExampleService_DoSomethingComplicated_result({success: result});
        output.writeMessageBegin("DoSomethingComplicated", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("DoSomethingComplicated", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.DoSomethingComplicated(args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new StingyExampleService_DoSomethingComplicated_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("DoSomethingComplicated", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("DoSomethingComplicated", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
